### PR TITLE
Link caller process

### PR DESCRIPTION
**Pull request by Hanspagh**
Sorry for the delay on this.
This is still a draft since I can not get the final test `shutting call process should kill sidekick` to parse
Maybe you can have a look.

Looking at this a bit more. It looks like the link is removed from the `Sidekick.Supervisor` after the call to `GenServer.stop()`, but the supervisor is not terminated

### CODE REVIEW

**Comment by sasa1977** [comment]
I took a quick look. Here's the minimal diff that fixes the test:

```diff
diff --git a/lib/sidekick/sidekick_supervisor.ex b/lib/sidekick/sidekick_supervisor.ex
index 733e4d8..4bc54dd 100644
--- a/lib/sidekick/sidekick_supervisor.ex
+++ b/lib/sidekick/sidekick_supervisor.ex
@@ -15,10 +15,14 @@ defmodule Sidekick.Supervisor do
     Process.unlink(caller_process)
     Process.link(linker_process)
 
-    {:ok, nil}
+    {:ok, %{owner_pid: linker_process}}
   end
 
-  def handle_info({:EXIT, _pid, _reason}, state), do: {:noreply, state}
+  def handle_info({:EXIT, pid, _reason}, state) do
+    if pid == state.owner_pid,
+      do: {:stop, :normal, state},
+      else: {:noreply, state}
+  end
 
   @impl GenServer
   def terminate(_reason, _state) do
```

This ensures that the top-level process in the sidekick node stops if the owner (what you called `linker_process`) has stopped.

**Comment by Hanspagh** [comment]
Thank you. I think I would never have figured that out. Is this related to Parent or what is the reason for having to handle the exit like that?

**Comment by sasa1977** [comment]
> Is this related to Parent or what is the reason for having to handle the exit like that?

Partially.

Normally, when a process dies, all of its linked processes are taken down. However, a process that traps exits will instead receive `{:EXIT, pid, reason}` message and needs to handle it.

One exception to this are OTP behaviours and parent processes. When we invoke e.g. `GenServer.start_link`, the starter process is treated as the parent of the gen server. If the starter process dies, the gen server will automatically stop, and you don't need to do anything to make it happen. This will happen even if the process is trapping exits. Basically, gen server will see that the exit message arrives from the parent, and it decides to stop without calling `handle_info`.

On the other hand, if any other linked process stops, and the gen server is trapping exits, you need to make a decision in `handle_info`.

In our case, the real parent of the sidekick supervisor is the process that started it, which is the process on the sidekick node that is invoked when the node is started. That process stops as soon as the supervisor process is started, but we want our supervisor to keep running. That's why we're unlinking from the physycal parent in `init`. As a result of that unlinking, the corresponding exit message won't be sent to the supervisor, and consequently it remains alive after it's parent stops.

On the other hand, we want to mimic a parent-child relationship between the starter process on the main node and the supervisor. That's why we link to that process in `init`. But this process isn't the physical parent, and so the supervisor won't automatically stop when the corresponding exit message arrives. Instead, we need to make this decision in the code. 

Does that make sense?

**Comment by Hanspagh** [comment]
That makes a lot of sense. Thanks a lot.
I was not aware that there was a difference between the physical parent and the processes you add as a link :).
I have updated the pr, and it works as expected. I will have one more look at the pr and after that I think it is ready for review

**Comment by sasa1977** [comment]
I was finally able to take a look. It looks pretty good, thanks! I pushed a few refactoring changes. I'm fine with merging this code, but I'd like to give you the opportunity to look at my changes and send your feedback/questions. 

Tests should definitely be expanded. I'll try to do this myself in a separate PR, hopefully sometime next week. In the meantime, if you're interested, I think that sidekick is in a good enough state to start the work on the managed container abstraction. I'll create an issue for this in the next few days, where we can discuss the basic idea.

**Comment by Hanspagh** [comment]
Sorry for not getting back to you earlier, the changes was looking good. Let's discuss the managed container. I already have some sample code I can share with you.

**Comment by sasa1977** [comment]
No worries, I've just opened #6 with some basic proposal. Could you please take a look and comment & submit your own suggestions.

**Pull request merged**
