### PR TITLE
Add note that `mox` is required not just in the test environment

### PR DESCRIPTION
**Pull request by aptinio**

### CODE REVIEW

**Comment by sasa1977** [comment]
Unfortunately this currently won't work because `ci` wraps `mox` to offer some convenience functions, and in addition it defines a mock module at compilation time. We could think about some alternatives, although my first impulse is that having to depend on `mox` at runtime is not particularly terrible.

**Comment by aptinio** [comment]
Thanks for clarifying that. This was just my knee jerk reaction after installing `ci` and seeing `mox` got installed along with it. Feel free to close this PR.

CI has been working great! Thanks for sharing it :heart:

**Comment by sasa1977** [comment]
We could add a comment just above the `mox` dep in mix.exs explaining why we don't use `only: :test`. WDYT?

**Comment by aptinio** [comment]
Sounds good! That should help users like me wondering about `mox` getting installed. :-)

**Comment by sasa1977** [comment]
Thank you!

**Pull request merged**
