### PR TITLE
Support latest telemetry

### PR DESCRIPTION
**Pull request by aptinio**

### CODE REVIEW

**Comment by sasa1977** [comment]
Thanks! Looks like there's a formatting error, possibly because of [this change](https://github.com/sasa1977/ci/pull/13/files#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308L63-R63).

**Comment by aptinio** [comment]
Oops, I was running Elixir 1.12 which formatted the file slightly differently. I removed the formatting changes. Thanks!

**Comment by sasa1977** [comment]
> Oops, I was running Elixir 1.12 which formatted the file slightly differently. I removed the formatting changes. Thanks!

I guess we could bump to the most recent Elixir :-)

**Comment by sasa1977** [comment]
Thank you!

**Pull request merged**
